[package]
name = "vobba"
version = "0.1.0"
authors = ["Luke Phelan <luke.phelan@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "0.7"

json = "*"